# Generated by Django 6.0.2 on 2026-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdetail",
            name="assign_to",
        ),
    ]
