# Generated by Django 6.0.2 on 2026-04-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_taskdetail_assign_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
    ]
