# Generated by Django 6.0.2 on 2026-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset_image",
            field=models.ImageField(blank=True, null=True, upload_to="task_asset"),
        ),
    ]
